In [1]:
import librosa
import keras
import os
import numpy as np
import scipy.io.wavfile as wav
import python_speech_features
from keras.utils import to_categorical
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix
from sklearn import metrics


Using TensorFlow backend.


In [2]:
data = []
labels = []

In [3]:
def extract_data_test(folder="data_yafi"):
    dirs = os.listdir(folder)
    counter = 0
    for dr in dirs:
        for file in os.listdir(folder+"/"+dr):
            if file[-4:]==".wav":
                #load wav
                audio, sfreq = librosa.load(folder+"/"+dr+"/"+file, sr=16000)
                mfcc = librosa.feature.mfcc(y=audio, sr=sfreq, n_mfcc=13)
                data.append(mfcc.T)
                labels.append(dr)
                print("loaded "+str(counter))
                counter+=1
                
                
                
    

In [4]:
def extract_data(folder="data_yafi"):
    dirs = os.listdir(folder)
    counter = 0
    for dr in dirs:
        for file in os.listdir(folder+"/"+dr):
            if file[-4:]==".wav":
                #load wav
                audio, sfreq = librosa.load(folder+"/"+dr+"/"+file)
                
    
                #normalisasi amplitudo
                audio_x = 2.*(audio - np.min(audio))/np.ptp(audio)-1
                #mfcc
                koef_mfcc = 13 #koef_mfcc = 7
                audio_n = python_speech_features.base.mfcc(audio_x,samplerate=16000,winlen=0.02,winstep=0.01,numcep=koef_mfcc,nfft=512,preemph=0.95,winfunc=np.hamming)
                data.append(audio_n)
                labels.append(dr)
                print("succes load :"+str(counter))
                counter+=1

In [5]:
extract_data_test()

loaded 0
loaded 1
loaded 2
loaded 3
loaded 4
loaded 5
loaded 6
loaded 7
loaded 8
loaded 9
loaded 10
loaded 11
loaded 12
loaded 13
loaded 14
loaded 15
loaded 16
loaded 17
loaded 18
loaded 19
loaded 20
loaded 21
loaded 22
loaded 23
loaded 24
loaded 25
loaded 26
loaded 27
loaded 28
loaded 29
loaded 30
loaded 31
loaded 32
loaded 33
loaded 34
loaded 35
loaded 36
loaded 37
loaded 38
loaded 39
loaded 40
loaded 41
loaded 42
loaded 43
loaded 44
loaded 45
loaded 46
loaded 47
loaded 48
loaded 49
loaded 50
loaded 51
loaded 52
loaded 53
loaded 54
loaded 55
loaded 56
loaded 57
loaded 58
loaded 59
loaded 60
loaded 61
loaded 62
loaded 63
loaded 64
loaded 65
loaded 66
loaded 67
loaded 68
loaded 69
loaded 70
loaded 71
loaded 72
loaded 73
loaded 74
loaded 75
loaded 76
loaded 77
loaded 78
loaded 79
loaded 80
loaded 81
loaded 82
loaded 83
loaded 84
loaded 85
loaded 86
loaded 87
loaded 88
loaded 89
loaded 90
loaded 91
loaded 92
loaded 93
loaded 94
loaded 95
loaded 96
loaded 97
loaded 98
loaded 99
loaded 100

loaded 763
loaded 764
loaded 765
loaded 766
loaded 767
loaded 768
loaded 769
loaded 770
loaded 771
loaded 772
loaded 773
loaded 774
loaded 775
loaded 776
loaded 777
loaded 778
loaded 779
loaded 780
loaded 781
loaded 782
loaded 783
loaded 784
loaded 785
loaded 786
loaded 787
loaded 788
loaded 789
loaded 790
loaded 791
loaded 792
loaded 793
loaded 794
loaded 795
loaded 796
loaded 797
loaded 798
loaded 799
loaded 800
loaded 801
loaded 802
loaded 803
loaded 804
loaded 805
loaded 806
loaded 807
loaded 808
loaded 809
loaded 810
loaded 811
loaded 812
loaded 813
loaded 814
loaded 815
loaded 816
loaded 817
loaded 818
loaded 819
loaded 820
loaded 821
loaded 822
loaded 823
loaded 824
loaded 825
loaded 826
loaded 827
loaded 828
loaded 829
loaded 830
loaded 831
loaded 832
loaded 833
loaded 834
loaded 835
loaded 836
loaded 837
loaded 838
loaded 839
loaded 840
loaded 841
loaded 842
loaded 843
loaded 844
loaded 845
loaded 846
loaded 847
loaded 848
loaded 849
loaded 850
loaded 851
loaded 852
loaded 853

loaded 1476
loaded 1477
loaded 1478
loaded 1479
loaded 1480
loaded 1481
loaded 1482
loaded 1483
loaded 1484
loaded 1485
loaded 1486
loaded 1487
loaded 1488
loaded 1489
loaded 1490
loaded 1491
loaded 1492
loaded 1493
loaded 1494
loaded 1495
loaded 1496
loaded 1497
loaded 1498
loaded 1499
loaded 1500
loaded 1501
loaded 1502
loaded 1503
loaded 1504
loaded 1505
loaded 1506
loaded 1507
loaded 1508
loaded 1509
loaded 1510
loaded 1511
loaded 1512
loaded 1513
loaded 1514
loaded 1515
loaded 1516
loaded 1517
loaded 1518
loaded 1519
loaded 1520
loaded 1521
loaded 1522
loaded 1523
loaded 1524
loaded 1525
loaded 1526
loaded 1527
loaded 1528
loaded 1529
loaded 1530
loaded 1531
loaded 1532
loaded 1533
loaded 1534
loaded 1535
loaded 1536
loaded 1537
loaded 1538
loaded 1539
loaded 1540
loaded 1541
loaded 1542
loaded 1543
loaded 1544
loaded 1545
loaded 1546
loaded 1547
loaded 1548
loaded 1549
loaded 1550
loaded 1551
loaded 1552
loaded 1553
loaded 1554
loaded 1555
loaded 1556
loaded 1557
loaded 1558
load

loaded 2165
loaded 2166
loaded 2167
loaded 2168
loaded 2169
loaded 2170
loaded 2171
loaded 2172
loaded 2173
loaded 2174
loaded 2175
loaded 2176
loaded 2177
loaded 2178
loaded 2179
loaded 2180
loaded 2181
loaded 2182
loaded 2183
loaded 2184
loaded 2185
loaded 2186
loaded 2187
loaded 2188
loaded 2189
loaded 2190
loaded 2191
loaded 2192
loaded 2193
loaded 2194
loaded 2195
loaded 2196
loaded 2197
loaded 2198
loaded 2199
loaded 2200
loaded 2201
loaded 2202
loaded 2203
loaded 2204
loaded 2205
loaded 2206
loaded 2207
loaded 2208
loaded 2209
loaded 2210
loaded 2211
loaded 2212
loaded 2213
loaded 2214
loaded 2215
loaded 2216
loaded 2217
loaded 2218
loaded 2219
loaded 2220
loaded 2221
loaded 2222
loaded 2223
loaded 2224
loaded 2225
loaded 2226
loaded 2227
loaded 2228
loaded 2229
loaded 2230
loaded 2231
loaded 2232
loaded 2233
loaded 2234
loaded 2235
loaded 2236
loaded 2237
loaded 2238
loaded 2239
loaded 2240
loaded 2241
loaded 2242
loaded 2243
loaded 2244
loaded 2245
loaded 2246
loaded 2247
load

loaded 2856
loaded 2857
loaded 2858
loaded 2859
loaded 2860
loaded 2861
loaded 2862
loaded 2863
loaded 2864
loaded 2865
loaded 2866
loaded 2867
loaded 2868
loaded 2869
loaded 2870
loaded 2871
loaded 2872
loaded 2873
loaded 2874
loaded 2875
loaded 2876
loaded 2877
loaded 2878
loaded 2879
loaded 2880
loaded 2881
loaded 2882
loaded 2883
loaded 2884
loaded 2885
loaded 2886
loaded 2887
loaded 2888
loaded 2889
loaded 2890
loaded 2891
loaded 2892
loaded 2893
loaded 2894
loaded 2895
loaded 2896
loaded 2897
loaded 2898
loaded 2899
loaded 2900
loaded 2901
loaded 2902
loaded 2903
loaded 2904
loaded 2905
loaded 2906
loaded 2907
loaded 2908
loaded 2909
loaded 2910
loaded 2911
loaded 2912
loaded 2913
loaded 2914
loaded 2915
loaded 2916
loaded 2917
loaded 2918
loaded 2919
loaded 2920
loaded 2921
loaded 2922
loaded 2923
loaded 2924
loaded 2925
loaded 2926
loaded 2927
loaded 2928
loaded 2929
loaded 2930
loaded 2931
loaded 2932
loaded 2933
loaded 2934
loaded 2935
loaded 2936
loaded 2937
loaded 2938
load

loaded 3543
loaded 3544
loaded 3545
loaded 3546
loaded 3547
loaded 3548
loaded 3549
loaded 3550
loaded 3551
loaded 3552
loaded 3553
loaded 3554
loaded 3555
loaded 3556
loaded 3557
loaded 3558
loaded 3559
loaded 3560
loaded 3561
loaded 3562
loaded 3563
loaded 3564
loaded 3565
loaded 3566
loaded 3567
loaded 3568
loaded 3569
loaded 3570
loaded 3571
loaded 3572
loaded 3573
loaded 3574
loaded 3575
loaded 3576
loaded 3577
loaded 3578
loaded 3579
loaded 3580
loaded 3581
loaded 3582
loaded 3583
loaded 3584
loaded 3585
loaded 3586
loaded 3587
loaded 3588
loaded 3589
loaded 3590
loaded 3591
loaded 3592
loaded 3593
loaded 3594
loaded 3595
loaded 3596
loaded 3597
loaded 3598
loaded 3599
loaded 3600
loaded 3601
loaded 3602
loaded 3603
loaded 3604
loaded 3605
loaded 3606
loaded 3607
loaded 3608
loaded 3609
loaded 3610
loaded 3611
loaded 3612
loaded 3613
loaded 3614
loaded 3615
loaded 3616
loaded 3617
loaded 3618
loaded 3619
loaded 3620
loaded 3621
loaded 3622
loaded 3623
loaded 3624
loaded 3625
load

loaded 4233
loaded 4234
loaded 4235
loaded 4236
loaded 4237
loaded 4238
loaded 4239
loaded 4240
loaded 4241
loaded 4242
loaded 4243
loaded 4244
loaded 4245
loaded 4246
loaded 4247
loaded 4248
loaded 4249
loaded 4250
loaded 4251
loaded 4252
loaded 4253
loaded 4254
loaded 4255
loaded 4256
loaded 4257
loaded 4258
loaded 4259
loaded 4260
loaded 4261
loaded 4262
loaded 4263
loaded 4264
loaded 4265
loaded 4266
loaded 4267
loaded 4268
loaded 4269
loaded 4270
loaded 4271
loaded 4272
loaded 4273
loaded 4274
loaded 4275
loaded 4276
loaded 4277
loaded 4278
loaded 4279
loaded 4280
loaded 4281
loaded 4282
loaded 4283
loaded 4284
loaded 4285
loaded 4286
loaded 4287
loaded 4288
loaded 4289
loaded 4290
loaded 4291
loaded 4292
loaded 4293
loaded 4294
loaded 4295
loaded 4296
loaded 4297
loaded 4298
loaded 4299
loaded 4300
loaded 4301
loaded 4302
loaded 4303
loaded 4304
loaded 4305
loaded 4306
loaded 4307
loaded 4308
loaded 4309
loaded 4310
loaded 4311
loaded 4312
loaded 4313
loaded 4314
loaded 4315
load

loaded 4921
loaded 4922
loaded 4923
loaded 4924
loaded 4925
loaded 4926
loaded 4927
loaded 4928
loaded 4929
loaded 4930
loaded 4931
loaded 4932
loaded 4933
loaded 4934
loaded 4935
loaded 4936
loaded 4937
loaded 4938
loaded 4939
loaded 4940
loaded 4941
loaded 4942
loaded 4943
loaded 4944
loaded 4945
loaded 4946
loaded 4947
loaded 4948
loaded 4949
loaded 4950
loaded 4951
loaded 4952
loaded 4953
loaded 4954
loaded 4955
loaded 4956
loaded 4957
loaded 4958
loaded 4959
loaded 4960
loaded 4961
loaded 4962
loaded 4963
loaded 4964
loaded 4965
loaded 4966
loaded 4967
loaded 4968
loaded 4969
loaded 4970
loaded 4971
loaded 4972
loaded 4973
loaded 4974
loaded 4975
loaded 4976
loaded 4977
loaded 4978
loaded 4979
loaded 4980
loaded 4981
loaded 4982
loaded 4983
loaded 4984
loaded 4985
loaded 4986
loaded 4987
loaded 4988
loaded 4989
loaded 4990
loaded 4991
loaded 4992
loaded 4993
loaded 4994
loaded 4995
loaded 4996
loaded 4997
loaded 4998
loaded 4999
loaded 5000
loaded 5001
loaded 5002
loaded 5003
load

loaded 5609
loaded 5610
loaded 5611
loaded 5612
loaded 5613
loaded 5614
loaded 5615
loaded 5616
loaded 5617
loaded 5618
loaded 5619
loaded 5620
loaded 5621
loaded 5622
loaded 5623
loaded 5624
loaded 5625
loaded 5626
loaded 5627
loaded 5628
loaded 5629
loaded 5630
loaded 5631
loaded 5632
loaded 5633
loaded 5634
loaded 5635
loaded 5636
loaded 5637
loaded 5638
loaded 5639
loaded 5640
loaded 5641
loaded 5642
loaded 5643
loaded 5644
loaded 5645
loaded 5646
loaded 5647
loaded 5648
loaded 5649
loaded 5650
loaded 5651
loaded 5652
loaded 5653
loaded 5654
loaded 5655
loaded 5656
loaded 5657
loaded 5658
loaded 5659
loaded 5660
loaded 5661
loaded 5662
loaded 5663
loaded 5664
loaded 5665
loaded 5666
loaded 5667
loaded 5668
loaded 5669
loaded 5670
loaded 5671
loaded 5672
loaded 5673
loaded 5674
loaded 5675
loaded 5676
loaded 5677
loaded 5678
loaded 5679
loaded 5680
loaded 5681
loaded 5682
loaded 5683
loaded 5684
loaded 5685
loaded 5686
loaded 5687
loaded 5688
loaded 5689
loaded 5690
loaded 5691
load

loaded 6297
loaded 6298
loaded 6299
loaded 6300
loaded 6301
loaded 6302
loaded 6303
loaded 6304
loaded 6305
loaded 6306
loaded 6307
loaded 6308
loaded 6309
loaded 6310
loaded 6311
loaded 6312
loaded 6313
loaded 6314
loaded 6315
loaded 6316
loaded 6317
loaded 6318
loaded 6319
loaded 6320
loaded 6321
loaded 6322
loaded 6323
loaded 6324
loaded 6325
loaded 6326
loaded 6327
loaded 6328
loaded 6329
loaded 6330
loaded 6331
loaded 6332
loaded 6333
loaded 6334
loaded 6335
loaded 6336
loaded 6337
loaded 6338
loaded 6339
loaded 6340
loaded 6341
loaded 6342
loaded 6343
loaded 6344
loaded 6345
loaded 6346
loaded 6347
loaded 6348
loaded 6349
loaded 6350
loaded 6351
loaded 6352
loaded 6353
loaded 6354
loaded 6355
loaded 6356
loaded 6357
loaded 6358
loaded 6359
loaded 6360
loaded 6361
loaded 6362
loaded 6363
loaded 6364
loaded 6365
loaded 6366
loaded 6367
loaded 6368
loaded 6369
loaded 6370
loaded 6371
loaded 6372
loaded 6373
loaded 6374
loaded 6375
loaded 6376
loaded 6377
loaded 6378
loaded 6379
load

loaded 6980
loaded 6981
loaded 6982
loaded 6983
loaded 6984
loaded 6985
loaded 6986
loaded 6987
loaded 6988
loaded 6989
loaded 6990
loaded 6991
loaded 6992
loaded 6993
loaded 6994
loaded 6995
loaded 6996
loaded 6997
loaded 6998
loaded 6999
loaded 7000
loaded 7001
loaded 7002
loaded 7003
loaded 7004
loaded 7005
loaded 7006
loaded 7007
loaded 7008
loaded 7009
loaded 7010
loaded 7011
loaded 7012
loaded 7013
loaded 7014
loaded 7015
loaded 7016
loaded 7017
loaded 7018
loaded 7019
loaded 7020
loaded 7021
loaded 7022
loaded 7023
loaded 7024
loaded 7025
loaded 7026
loaded 7027
loaded 7028
loaded 7029
loaded 7030
loaded 7031
loaded 7032
loaded 7033
loaded 7034
loaded 7035
loaded 7036
loaded 7037
loaded 7038
loaded 7039
loaded 7040
loaded 7041
loaded 7042
loaded 7043
loaded 7044
loaded 7045
loaded 7046
loaded 7047
loaded 7048
loaded 7049
loaded 7050
loaded 7051
loaded 7052
loaded 7053
loaded 7054
loaded 7055
loaded 7056
loaded 7057
loaded 7058
loaded 7059
loaded 7060
loaded 7061
loaded 7062
load

loaded 7672
loaded 7673
loaded 7674
loaded 7675
loaded 7676
loaded 7677
loaded 7678
loaded 7679
loaded 7680
loaded 7681
loaded 7682
loaded 7683
loaded 7684
loaded 7685
loaded 7686
loaded 7687
loaded 7688
loaded 7689
loaded 7690
loaded 7691
loaded 7692
loaded 7693
loaded 7694
loaded 7695
loaded 7696
loaded 7697
loaded 7698
loaded 7699
loaded 7700
loaded 7701
loaded 7702
loaded 7703
loaded 7704
loaded 7705
loaded 7706
loaded 7707
loaded 7708
loaded 7709
loaded 7710
loaded 7711
loaded 7712
loaded 7713
loaded 7714
loaded 7715
loaded 7716
loaded 7717
loaded 7718
loaded 7719
loaded 7720
loaded 7721
loaded 7722
loaded 7723
loaded 7724
loaded 7725
loaded 7726
loaded 7727
loaded 7728
loaded 7729
loaded 7730
loaded 7731
loaded 7732
loaded 7733
loaded 7734
loaded 7735
loaded 7736
loaded 7737
loaded 7738
loaded 7739
loaded 7740
loaded 7741
loaded 7742
loaded 7743
loaded 7744
loaded 7745
loaded 7746
loaded 7747
loaded 7748
loaded 7749
loaded 7750
loaded 7751
loaded 7752
loaded 7753
loaded 7754
load

loaded 8363
loaded 8364
loaded 8365
loaded 8366
loaded 8367
loaded 8368
loaded 8369
loaded 8370
loaded 8371
loaded 8372
loaded 8373
loaded 8374
loaded 8375
loaded 8376
loaded 8377
loaded 8378
loaded 8379
loaded 8380
loaded 8381
loaded 8382
loaded 8383
loaded 8384
loaded 8385
loaded 8386
loaded 8387
loaded 8388
loaded 8389
loaded 8390
loaded 8391
loaded 8392
loaded 8393
loaded 8394
loaded 8395
loaded 8396
loaded 8397
loaded 8398
loaded 8399
loaded 8400
loaded 8401
loaded 8402
loaded 8403
loaded 8404
loaded 8405
loaded 8406
loaded 8407
loaded 8408
loaded 8409
loaded 8410
loaded 8411
loaded 8412
loaded 8413
loaded 8414
loaded 8415
loaded 8416
loaded 8417
loaded 8418
loaded 8419
loaded 8420
loaded 8421
loaded 8422
loaded 8423
loaded 8424
loaded 8425
loaded 8426
loaded 8427
loaded 8428
loaded 8429
loaded 8430
loaded 8431
loaded 8432
loaded 8433
loaded 8434
loaded 8435
loaded 8436
loaded 8437
loaded 8438
loaded 8439
loaded 8440
loaded 8441
loaded 8442
loaded 8443
loaded 8444
loaded 8445
load

loaded 9054
loaded 9055
loaded 9056
loaded 9057
loaded 9058
loaded 9059
loaded 9060
loaded 9061
loaded 9062
loaded 9063
loaded 9064
loaded 9065
loaded 9066
loaded 9067
loaded 9068
loaded 9069
loaded 9070
loaded 9071
loaded 9072
loaded 9073
loaded 9074
loaded 9075
loaded 9076
loaded 9077
loaded 9078
loaded 9079
loaded 9080
loaded 9081
loaded 9082
loaded 9083
loaded 9084
loaded 9085
loaded 9086
loaded 9087
loaded 9088
loaded 9089
loaded 9090
loaded 9091
loaded 9092
loaded 9093
loaded 9094
loaded 9095
loaded 9096
loaded 9097
loaded 9098
loaded 9099
loaded 9100
loaded 9101
loaded 9102
loaded 9103
loaded 9104
loaded 9105
loaded 9106
loaded 9107
loaded 9108
loaded 9109
loaded 9110
loaded 9111
loaded 9112
loaded 9113
loaded 9114
loaded 9115
loaded 9116
loaded 9117
loaded 9118
loaded 9119
loaded 9120
loaded 9121
loaded 9122
loaded 9123
loaded 9124
loaded 9125
loaded 9126
loaded 9127
loaded 9128
loaded 9129
loaded 9130
loaded 9131
loaded 9132
loaded 9133
loaded 9134
loaded 9135
loaded 9136
load

In [6]:
labels_encoded = []
for i in labels:
    if i == "nyala":
        labels_encoded.append(0)
    elif i=="mati":
        labels_encoded.append(1)
    else :
        labels_encoded.append(2)
data_np = keras.preprocessing.sequence.pad_sequences(data, maxlen=None, dtype='int32', padding='pre', truncating='pre', value=0.0)
labels_encoded = np.vstack(labels_encoded)
labels_encoded = to_categorical(labels_encoded)

In [7]:
data_np.shape

(9450, 63, 13)

In [8]:
length = 9450
num_train = 6000
index = np.random.randint(0, length, size=length)
train_X = data_np[index[0:num_train]]
train_Y= labels_encoded[index[0:num_train]]
test_X= data_np[index[num_train:]]
test_Y= labels_encoded[index[num_train:]]

In [9]:
def create_model_lstm():
    model = keras.models.Sequential([
            keras.layers.LSTM(15, return_sequences=True, input_shape=[None, 13]),
            keras.layers.LSTM(15),
            keras.layers.Dense(3, activation='softmax')
            ])
    return model

In [10]:
model = create_model_lstm()
optimizer = keras.optimizers.Adam(lr=0.01)
model.compile(loss="categorical_crossentropy", optimizer= optimizer, metrics=["acc"])
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_1 (LSTM)                (None, None, 15)          1740      
_________________________________________________________________
lstm_2 (LSTM)                (None, 15)                1860      
_________________________________________________________________
dense_1 (Dense)              (None, 3)                 48        
Total params: 3,648
Trainable params: 3,648
Non-trainable params: 0
_________________________________________________________________


In [ ]:
history = model.fit(train_X, train_Y, epochs=25, validation_data = (test_X, test_Y))

In [ ]:
history_dict = history.history
loss_values = history_dict['loss']
val_loss_values = history_dict['val_loss']
epochs = range(1, len(loss_values) + 1)
plt.plot(epochs, loss_values, 'bo', label='Training loss')
plt.plot(epochs, val_loss_values, 'b', label='Validation loss')
plt.title('Training and validation loss')
plt.xlabel('Epochs')
plt.ylabel('Loss')
plt.legend()
plt.show()

In [ ]:
plt.clf()
acc_values = history_dict['acc']
val_acc_values = history_dict['val_acc']
plt.plot(epochs, acc_values, 'bo', label='Training acc')
plt.plot(epochs, val_acc_values, 'b', label='Validation acc')
plt.title('Training and validation accuracy')
plt.xlabel('Epochs')
plt.ylabel('Loss')
plt.legend()
plt.show()

In [ ]:
model.save_weights('lstm_model_koef_13.h5')

In [ ]:
hasil = model.evaluate(x = train_X, y=train_Y)

In [ ]:
hasil[1]

CONFUSION MATRIX

In [11]:
def get_label(plain_label):
    labels = ["nyala", "mati", "lain"]
    result = []
    for label in plain_label:
        result.append(labels[np.argmax(label)])
    return result

In [12]:
true_train_list = []
pred_train_list = []
true_validasi_list = []
pred_validasi_list = []

In [13]:
length_cross = 9450

index_cross = np.random.randint(0, length_cross, size=length_cross)
cross_data = data_np[index_cross]
cross_label = labels_encoded[index_cross]

k=10
num_validation_samples = len(cross_data) // k
validation_scores = []
for fold in range(k):
    validation_data = cross_data[num_validation_samples * fold:num_validation_samples * (fold + 1)]
    validation_data_y = cross_label[num_validation_samples * fold:num_validation_samples * (fold + 1)]
    training_data = np.vstack((cross_data[:num_validation_samples * fold], cross_data[num_validation_samples * (fold + 1):]))
    training_data_y = np.vstack((cross_label[:num_validation_samples * fold], cross_label[num_validation_samples * (fold + 1):]))
    cross_model = create_model_lstm()
    optimizer = keras.optimizers.Adam(lr=0.01)
    cross_model.compile(loss="categorical_crossentropy", optimizer= optimizer, metrics=["acc"])
    cross_model.fit(x = training_data, y = training_data_y, epochs=25)
    
    train_label = cross_model.predict(training_data)
    validasi_label = cross_model.predict(validation_data)
    train_label = get_label(train_label)
    validasi_label = get_label(validasi_label)
    pred_train_list.append(train_label)
    pred_validasi_list.append(validasi_label)
    
    true_train_list.append(get_label(training_data_y))
    true_validasi_list.append(get_label(validation_data_y))
    
    validation_score = cross_model.evaluate(x=validation_data, y = validation_data_y)
    validation_scores.append(validation_score[1])

Epoch 1/25
8505/8505 [==============================] - 13s 2ms/step - loss: 0.4857 - acc: 0.7915
Epoch 2/25
8505/8505 [==============================] - 11s 1ms/step - loss: 0.2428 - acc: 0.9131
Epoch 3/25
8505/8505 [==============================] - 11s 1ms/step - loss: 0.2152 - acc: 0.9293
Epoch 4/25
8505/8505 [==============================] - 11s 1ms/step - loss: 0.1209 - acc: 0.9618
Epoch 5/25
8505/8505 [==============================] - 11s 1ms/step - loss: 0.0962 - acc: 0.9707
Epoch 6/25
8505/8505 [==============================] - 10s 1ms/step - loss: 0.0833 - acc: 0.9761
Epoch 7/25
8505/8505 [==============================] - 10s 1ms/step - loss: 0.0654 - acc: 0.9814
Epoch 8/25
8505/8505 [==============================] - 10s 1ms/step - loss: 0.0873 - acc: 0.9746
Epoch 9/25
8505/8505 [==============================] - 10s 1ms/step - loss: 0.0700 - acc: 0.9792
Epoch 10/25
8505/8505 [==============================] - 10s 1ms/step - loss: 0.0612 - acc: 0.9827
Epoch 11/25
8505/85

8505/8505 [==============================] - 10s 1ms/step - loss: 0.0676 - acc: 0.9792
Epoch 12/25
8505/8505 [==============================] - 9s 1ms/step - loss: 0.0413 - acc: 0.9886
Epoch 13/25
8505/8505 [==============================] - 8s 997us/step - loss: 0.0422 - acc: 0.9853
Epoch 14/25
8505/8505 [==============================] - 9s 1ms/step - loss: 0.0369 - acc: 0.9884
Epoch 15/25
8505/8505 [==============================] - 8s 989us/step - loss: 0.0529 - acc: 0.9830
Epoch 16/25
8505/8505 [==============================] - 9s 1ms/step - loss: 0.0416 - acc: 0.9865
Epoch 17/25
8505/8505 [==============================] - 8s 983us/step - loss: 0.0416 - acc: 0.9874
Epoch 18/25
8505/8505 [==============================] - 9s 1ms/step - loss: 0.0318 - acc: 0.9921
Epoch 19/25
8505/8505 [==============================] - 9s 1ms/step - loss: 0.0326 - acc: 0.9913
Epoch 20/25
8505/8505 [==============================] - 8s 992us/step - loss: 0.0352 - acc: 0.9894
Epoch 21/25
8505/8505 [

In [14]:
def counts_from_confusion(confusion):
    """
    Obtain TP, FN FP, and TN for each class in the confusion matrix
    """

    counts_list = []

    # Iterate through classes and store the counts
    for i in range(confusion.shape[0]):
        tp = confusion[i, i]

        fn_mask = np.zeros(confusion.shape)
        fn_mask[i, :] = 1
        fn_mask[i, i] = 0
        fn = np.sum(np.multiply(confusion, fn_mask))

        fp_mask = np.zeros(confusion.shape)
        fp_mask[:, i] = 1
        fp_mask[i, i] = 0
        fp = np.sum(np.multiply(confusion, fp_mask))

        tn_mask = 1 - (fn_mask + fp_mask)
        tn_mask[i, i] = 0
        tn = np.sum(np.multiply(confusion, tn_mask))

        counts_list.append({'Class': i,
                            'TP': tp,
                            'FN': fn,
                            'FP': fp,
                            'TN': tn})

    return counts_list

In [16]:
from numpy import asarray
from numpy import savetxt
from sklearn.metrics import accuracy_score
for i in range(0, 10):
    print("\n")
    print("FOLD "+str(i+1)+":")
    print("--TRAINING--")
    print("nyala, mati, lain")
    print(confusion_matrix(true_train_list[i], pred_train_list[i] ))
    print (counts_from_confusion(confusion_matrix(true_train_list[i], pred_train_list[i])))
    print(metrics.classification_report(true_train_list[i], pred_train_list[i], digits=3))
    savetxt("lstm 13 conf tr "+str(i)+'.csv',confusion_matrix(true_train_list[i], pred_train_list[i]),delimiter = '/')
    savetxt("lstm 13 tp fn tr "+str(i)+'.csv',counts_from_confusion(confusion_matrix(true_train_list[i], pred_train_list[i])),delimiter = '/', fmt='%s')
    print(accuracy_score(true_train_list[i], pred_train_list[i]))
    
    print("--VALIDATION--")
    print("nyala, mati, lain")
    print(confusion_matrix(true_validasi_list[i], pred_validasi_list[i] ))
    print (counts_from_confusion(confusion_matrix(true_validasi_list[i], pred_validasi_list[i])))
    print(metrics.classification_report(true_validasi_list[i], pred_validasi_list[i], digits=3))
    savetxt("lstm 13 conf val "+str(i)+'.csv',confusion_matrix(true_validasi_list[i], pred_validasi_list[i]),delimiter = '/')
    savetxt("lstm 13 tp fn val "+str(i)+'.csv',counts_from_confusion(confusion_matrix(true_validasi_list[i], pred_validasi_list[i])),delimiter = '/', fmt='%s')
    print(accuracy_score(true_validasi_list[i], pred_validasi_list[i]))



FOLD 1:
--TRAINING--
nyala, mati, lain
[[2843    5    9]
 [  62 2788    8]
 [  19    1 2770]]
[{'Class': 0, 'TP': 2843, 'FN': 14.0, 'FP': 81.0, 'TN': 5567.0}, {'Class': 1, 'TP': 2788, 'FN': 70.0, 'FP': 6.0, 'TN': 5641.0}, {'Class': 2, 'TP': 2770, 'FN': 20.0, 'FP': 17.0, 'TN': 5698.0}]
              precision    recall  f1-score   support

        lain      0.972     0.995     0.984      2857
        mati      0.998     0.976     0.987      2858
       nyala      0.994     0.993     0.993      2790

    accuracy                          0.988      8505
   macro avg      0.988     0.988     0.988      8505
weighted avg      0.988     0.988     0.988      8505

0.98777189888301
--VALIDATION--
nyala, mati, lain
[[315   0   2]
 [  5 319   1]
 [  6   0 297]]
[{'Class': 0, 'TP': 315, 'FN': 2.0, 'FP': 11.0, 'TN': 617.0}, {'Class': 1, 'TP': 319, 'FN': 6.0, 'FP': 0.0, 'TN': 620.0}, {'Class': 2, 'TP': 297, 'FN': 6.0, 'FP': 3.0, 'TN': 639.0}]
              precision    recall  f1-score   support

              precision    recall  f1-score   support

        lain      0.991     0.998     0.994      2853
        mati      0.998     0.998     0.998      2856
       nyala      1.000     0.993     0.997      2796

    accuracy                          0.996      8505
   macro avg      0.996     0.996     0.996      8505
weighted avg      0.996     0.996     0.996      8505

0.9962375073486185
--VALIDATION--
nyala, mati, lain
[[317   3   1]
 [  0 326   1]
 [  4   0 293]]
[{'Class': 0, 'TP': 317, 'FN': 4.0, 'FP': 4.0, 'TN': 620.0}, {'Class': 1, 'TP': 326, 'FN': 1.0, 'FP': 3.0, 'TN': 615.0}, {'Class': 2, 'TP': 293, 'FN': 4.0, 'FP': 2.0, 'TN': 646.0}]
              precision    recall  f1-score   support

        lain      0.988     0.988     0.988       321
        mati      0.991     0.997     0.994       327
       nyala      0.993     0.987     0.990       297

    accuracy                          0.990       945
   macro avg      0.991     0.990     0.990       945
weighted avg  